azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    authorization-clients:
      api:
        scopes:
          - api://44301ed3-d324-4fab-b475-620e0e893390/Read.Notes

logging:
  level:
    org:
      springframework:
        security: DEBUG