azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    authorization-clients:
      api:
        scopes:
          - api://692c1e91-7e1c-40fa-ae8d-66a888f1a6c9/User.Read

logging:
  level:
    org:
      springframework:
        security: DEBUG